DEBUG = True
THREADS_PER_PAGE = 4
CSRF_ENABLED     = True
CSRF_SESSION_KEY = b'4db6jY75PDHbkm7SPFAg'
UPLOAD_FOLDER = 'uploads'

HISTOGRAM_FILENAME='Histogram_log10D.csv'
FILTERED_FILENAME='Filtered_log10D.csv'
MSD_FILENAME='Filtered_AllROI-MSD.txt'
MSD_POINTS=10
TIME_INTERVAL=0.02
ENCODING='ISO-8859-1'
LOG_COLUMN='D(µm²/s)'
DIFF_COLUMN='log10D'
MINLIMIT=-4
MAXLIMIT=1
BINWIDTH=0.2
THRESHOLD=-1.6